project: 
  type: website
  
website: 
  page-navigation: false
  title: "MY Clone of Making sharable documents with Quarto" 
  site-url: "https://mysheepb.github.io/quarto-website-tutorial" 
  repo-url: https://github.com/mysheepb/quarto-website-tutorial 
  repo-actions: [edit, issue]
  reader-mode: true
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: false
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/mysheepb/quarto-website-tutorial
        text: "Quarto website tutorial"
      - icon: twitter-x
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - Altair.qmd
      - explore.qmd
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
